version: '2'
services:
  server:
    build: .
    ports:
      - 80:3000
      - 443:3000
    links:
      - db
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGODB_USER: "${db_user_env}"
      MONGODB_DATABASE: "${dbname_env}"
      MONGODB_PASS: "${db_pass}"